### PR TITLE
Fixed uninitialized PID.ip & PID.pid failure (#6)

### PR DESCRIPTION
**Pull request by LibertyPaul**
Solution to problem described under #6 
Worked for me -- 1 hour and no crashes.

### CODE REVIEW

**Comment by stek29** [comment]
thank you

**Comment by stek29** [comment]
@LibertyPaul have you actually ever got crash because of assert in server?

Here:
https://github.com/TelegramMessenger/MTProxy/blob/cdd348294d86e74442bb29bd6767e48321259bec/net/net-tcp-rpc-server.c#L240-L242

The only place where `tcp_rpcs_send_handshake_packet` is referenced is here:
https://github.com/TelegramMessenger/MTProxy/blob/cdd348294d86e74442bb29bd6767e48321259bec/net/net-tcp-rpc-server.c#L422-L429

As you can see, it's called only if `tcp_rpcs_process_handshake_packet` succeeds.
And `tcp_rpcs_process_handshake_packet` starts with this code:

https://github.com/TelegramMessenger/MTProxy/blob/cdd348294d86e74442bb29bd6767e48321259bec/net/net-tcp-rpc-server.c#L270-L275

I can't see any way to reach `tcp_rpcs_send_handshake_packet` with `PID.ip` not being initialized.

So -- have you actually got any crashes there, or you've just thought it'd be a good idea to change both server and client handshake sending funcs?

**Comment by LibertyPaul** [comment]
Hi @stek29 

Yes, I've got such crash every time I launch **MTProxy** on my Hetzner Ubuntu 18.04 machine.

I've spent a few hours with GDB to find what is the reason but hasn't success (probably because multi-threading is involved). Later I've added initialization in place of **PID.ip** assert, and got new one in **PID.pid**, fixed it as well and **MTProxy** started to work fine.

Thanks for accepting!

P.S. To debug it I was manually adding `-g` flag to compiler, maybe it will be feasible to add `make debug` target?

**Comment by stek29** [comment]
I’ll redo this and push updated sources in a couple of hours. Please check if they don’t crash for you (they should not).
Also, when crashes happen because of assert, it prints backtrace and place where assetion has failed.

**Comment by LibertyPaul** [comment]
@stek29, I've tested your version. It seems to be working.
I will open new issue in case of any problems.
Thanks!

**Pull request merged**
