### PR TITLE
Making README more friendly and readable

### PR DESCRIPTION
**Pull request by L11R**
I made it even more fancy than #49 and #48

### CODE REVIEW

**Comment by kasramoslehi** [comment]
Need it

**Comment by p1ratrulezzz** [comment]
Looks much better than the usual txt file. Will be also great to add info about multiple secrets:

-S secret1 -S secret2

Can be a good solution if you want to have different passwords for connecting, this feature is not documented at all.

**Comment by L11R** [comment]
@p1ratrulezzz I have added info about multiple secrets. There is still questionable info about IPv6 servers #8

**Comment by p1ratrulezzz** [comment]
I believe it means "connect to telegram servers via ipv6" but i didn't check if this flag works at all

**Comment by L11R** [comment]
@p1ratrulezzz have just seen you fork. Added info about systemd :)

**Comment by stek29** [comment]
Thank you!

**Pull request merged**
